config/routes.rb
Rails.application.routes.draw do

  resource :inside, only: [:show]
  resources :collections, only: [:index]
  resources :news, only: [:index] do
    collection do
      get "grand-opening" => "news#grand_opening"
    end
  end

  resource :location, only: [:show] do
    collection do
      post "leave-message" => "locations#leave_message"
    end
  end

  get "/terms-and-policies" => "terms#terms_and_policies"

  root to: "welcome#new_coming_soon"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :set_page_title
  helper_method :set_page_group
  helper_method :page_title

  protected

  def set_page_title(title = '')
    @page_title = title
  end

  def set_page_group(group)
    @page_group = group
  end

  def page_title
    @page_title.blank? ? 'Beawelry' : @page_title
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :change_page_group

  def index
    set_page_title "Collections | Beawelry"
  end

  private

  def change_page_group
    set_page_group "collections"
  end
end

app/controllers/insides_controller.rb
class InsidesController < ApplicationController
  def show
    set_page_title "Inside | Beawelry"
    set_page_group "inside"
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :change_page_group

  def show
    set_page_title "Store Location | Beawelry"
  end

  def leave_message
    name = params[:name] || ''
    email = params[:email] || ''
    message   = params[:message] || []

    if name.blank? or email.blank? or message.strip.blank?
      render text: ''
      return
    end

    telephone = params[:telephone] || ''

    Mailer.enquiry_mail({ name: name, email: email, message: message, telephone: telephone }).deliver
  end

  private

  def change_page_group
    set_page_group 'location'
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :change_page_group

  def index
    set_page_title "News | Beawelry"
  end

  def grand_opening
    set_page_title "Grand Opening | Beawelry"
  end

  private

  def change_page_group
    set_page_group 'news'
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :change_page_group

  def terms_and_policies
    set_page_title "Terms & Policies | Beawelry"
  end

  private

  def change_page_group
    set_page_group "terms"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'

  def landing
    render template: 'welcome/landing', layout: false
  end

  def coming_soon
    set_page_title "Coming Soon"
    render template: 'welcome/coming_soon', layout: false
  end

  def new_coming_soon
    set_page_title "Bare your heart | Beawelry"
    render template: 'welcome/new_coming_soon', layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/insides/show.html.erb
<header id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active" ></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for Slides -->
  <div class="carousel-inner">
    <div class="item active">
      <div class="container">
        <div class="col-md-12">
          <h1>THE NEW WAY <br> <span>OF GIVING</span></h1>
        </div>
        <div class="col-md-6">
          <p>
            Beawelry reinvents the traditional perception of jewelry; from precious and valuable material to object of emotional representation. We strive to provide the most warming and beautiful experience of giving, receiving, and wearing.
          </p>
          <p>
            Beawelry combines the delicacy of jewelry with the warmth of our Beawelry Bear(hence our name). The Beawelry Bear is copyright registered worldwide and designed specifically to take part in the giving experience by being a lovable doll, a delicate piece of jewelry, and a ring holder.
          </p>
          <p>
            Beawelry provides premium gifts that can be personalized to create a new giving experience. We wish to help you express your emotions to your loved ones for all your special occasions. We invite you to bare your heart.
          </p>
        </div>
        <div class="col-md-6">
          <div class=" slider img-responsive ">
            <figure class="fourimage">
              <%= image_tag 'beawelry-new-way-01.jpg' %>
              <%= image_tag 'beawelry-new-way-02.jpg' %>
              <%= image_tag 'beawelry-new-way-03.jpg' %>
              <%= image_tag 'beawelry-new-way-04.jpg' %>
              <%= image_tag 'beawelry-new-way-01.jpg' %>
            </figure>
          </div>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="container">
        <div class="col-md-12">
           <h1>THE<br> <span>EXCLUSIVITY</span></h1>
        </div>
        <div class="col-md-6">

          <p>
            We want to ensure that every product you purchase with us is uniquely and truly made for you. With our new laser engraving technology; you can have a product that is exclusively yours within minutes. We invite you to join us at our store to experience our new personalization software which allows you to record any message onto our signature premium envelope charms and rings. Beawelry wishes to be a medium in which you express your emotions to your special someone.
          </p>

        </div>
        <div class="col-md-6">
          <div class=" slider img-responsive ">
            <figure class="treeimage">
              <%= image_tag '2-THE-EXCLUSIVITY-01.jpg' %>
              <%= image_tag '2-THE-EXCLUSIVITY-02.jpg' %>
              <%= image_tag '2-THE-EXCLUSIVITY-03.jpg' %>
              <%= image_tag '2-THE-EXCLUSIVITY-01.jpg' %>
            </figure>
          </div>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="container">
        <div class="col-md-12">
           <h1>OUR <br> <span>COMPANY</span></h1>
        </div>
        <div class="col-md-6">

          <p>
            Our jewelry pieces are made by a selected team of craftsmen with more than twenty-years of experience. We strive to create wearable jewelry for everyday use while ensuring that every piece is produced at the highest standard and meticulous attention to detail. In order to make sure that every piece of jewelry is executed to perfection, our manufacturing method combines the precision of technology with the delicacy of the human hand.
          </p>

        </div>
        <div class="col-md-6">
          <div class=" slider img-responsive ">
            <figure class="treeimage">
              <%= image_tag '3-OUR-COMPANY-01.jpg' %>
              <%= image_tag '3-OUR-COMPANY-02.jpg' %>
              <%= image_tag '3-OUR-COMPANY-03.jpg' %>
              <%= image_tag '3-OUR-COMPANY-01.jpg' %>
            </figure>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= render partial: 'shared/carousel_control' %>
</header>
<!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimal-ui" />
    <meta name="description" content="Beawelry reinvents the traditional perception of jewelry; from precious and valuable material to object of emotional representation. We strive to provide the most warming and beautiful experience of giving, receiving, and wearing">
    <meta name="author" content="Beawelry">

    <link rel="shortcut icon" href="<%= asset_path('favicon.ico') %>" type="image/x-icon">
    <link rel="icon" href="<%= asset_path('favicon.ico') %>" type="image/x-icon">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">
    <!--
    /**
     * @license
     * MyFonts Webfont Build ID 2883025, 2014-09-14T04:22:41-0400
     *
     * The fonts listed in this notice are subject to the End User License
     * Agreement(s) entered into by the website owner. All other parties are
     * explicitly restricted from using the Licensed Webfonts(s).
     *
     * You may obtain a valid license at the URLs below.
     *
     * Webfont: Copperplate Light by URW++
     * URL: http://www.myfonts.com/fonts/urw/copperplate/t-light/
     * Copyright: (URW)++,Copyright 2006 by (URW)++ Design &amp; Development
     *
     * Webfont: Firmin Didot URW Roman by URW++
     * URL: http://www.myfonts.com/fonts/urw/firmin-didot/urw-t-roman/
     * Copyright: Copyright 2010 URW++ Design &amp; Development Hamburg
     *
     *
     * License: http://www.myfonts.com/viewlicense?type=web&buildid=2883025
     * Licensed pageviews: 10,000
     *
     * © 2014 MyFonts Inc
    */

    -->
  </head>

  <body>
    <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-W9RF2S"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-W9RF2S');</script>
    <!-- End Google Tag Manager -->

    <div class="brand gradient-bg-header">
      <%= image_tag "beawelry_logo_02.png" %>
    </div>
    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header gradient-bg-header">
          <button type="button" class="navbar-toggle gradient-bg-header" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
          <a class="navbar-brand" href="/">
            <%= image_tag 'beawelry_logo_03.png' %>
          </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li >
              <%= link_to 'inside', inside_path, class: (@page_group == 'inside' ? 'active' : '') %>
            </li>
            <li>
              <%= link_to 'collection', collections_path, class: (@page_group == 'collections' ? 'active' : '') %>
            </li>
            <li>
              <%= link_to 'news', news_index_path, class: (@page_group == 'news' ? 'active' : '') %>
            </li>
            <li>
              <%= link_to 'store location', location_path, class: (@page_group == 'location' ? 'active' : '') %>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

    <%= yield %>

    <footer class="gradient-bg-header">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="footer-left">
              <div class="padding-top10">Beawelry &reg; 2014 &copy;</div>
            </div>
            <div class="footer-right">
              <ul class="social-footer">
                <li>
                  <%= link_to 'Terms & Policies', terms_and_policies_path %>
                </li>
                <li>
                  <a href="https://www.facebook.com/Beawelry" target="_blank" title="Beawelry's facebook">
                  <i class="fa fa-facebook"></i></a>
                </li>
                <li>
                  <a href="http://instagram.com/beawelry" title="Beawelry's instagram">
                  <i class="fa fa-instagram"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <link href="//hello.myfonts.net/count/2bfdd1" media="all" rel="stylesheet" />
  </body>
</html>

app/views/locations/show.html.erb
<header id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active" ></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
  </ol>

  <!-- Wrapper for Slides -->
  <div class="carousel-inner">
      <div class="item active">
          <div class="container">
              <div class="col-md-6">
                  <h1>BEAWELRY STORE <br/><span>at SIAM CENTER</span></h1>
                  <p class="text-contact">
                     We invite you to bare your heart.
                  </p>
                  <p class="text-contact">
                      Siam Center(floor 1) ,Bangkok,Thailand
                  </p>
                  <p class="text-contact">
                      10:00 AM. - 10:00 PM.
                  </p>
                  <p class="text-contact">
                      Tel.  02-658-1068 <br/>Email : customer@beawelry.com
                  </p>


              </div>
              <div class="col-md-6">
                <%= image_tag 'beawelry-map.png', class: 'img-responsive' %>
              </div>
          </div>
      </div>
      <div class="item">
          <div class="container">

              <div class="col-md-6">
                  <h1>ENQUIRIES</h1>
                  <p>
                     We would love to hear your thoughts, comments and questions. Please leave your suggestion below and we will get back to you as soon as possible.
                  </p>

                  <%= form_tag leave_message_location_path, method: :post do %>
                    <div class="row">
                      <div class="form-group col-lg-4">
                        <label>Name</label>
                        <%= text_field_tag 'name', '', class: 'form-control', required: true %>
                      </div>
                      <div class="form-group col-lg-4">
                        <label>Email Address</label>
                        <%= email_field_tag 'email', '', class: 'form-control', required: true %>
                      </div>
                      <div class="form-group col-lg-4">
                        <label>Phone Number</label>
                        <%= text_field_tag 'telephone', '', class: 'form-control' %>
                      </div>
                      <div class="clearfix"></div>
                      <div class="form-group col-lg-12">
                        <label>Message</label>
                        <%= text_area_tag 'message', '', class: 'form-control', required: true, rows: 6 %>
                      </div>
                      <div class="form-group col-lg-12">
                          <input type="hidden" name="save" value="contact">
                          <button type="submit" class="btn btn-default">Submit</button>
                      </div>
                    </div>
                  <% end %>
              </div>
          </div>
      </div>
  </div>

  <%= render partial: 'shared/carousel_control' %>

</header>
<!-- /.container -->

app/views/news/grand_opening.html.erb
<div class="container full-height">
    <div class="header-title">
        <ul class="list-inline">
            <li>
                <%= link_to 'home', inside_path %>
            </li>
            <li>
                <%= link_to 'news', news_index_path %>
            </li>
            <li>Join us</li>
        </ul>
    </div>
    <div class="col-md-3">
        <%= image_tag 'beawelry.jpg', class: 'img-responsive' %>
    </div>
    <div class="col-md-9">
        <h1>Join Us</h1>
         <ul class="list-inline">
                <li><i class="fa fa-calendar"></i> 22/10/2014</li>
                <li></li>
            </ul>
        <p>
            Bare your heart starting this October 22nd, 2014 on the first floor of Siam Center. We hope to see you soon.
        </p>


    </div>
</div>
<!-- /.container -->

app/views/news/index.html.erb
<div class="container full-height">
    <div class="box-news col-md-6">
        <div class="col-md-4">
          <%= image_tag "beawelry.jpg", class: 'img-responsive' %>
        </div>
        <div class="col-md-8">
            <h3>Join us</h3>
            <ul class="list-inline">
                <li><i class="fa fa-calendar"></i> 22/10/2014</li>
                <li></li>
            </ul>
            <p>Bare your heart starting this October 22nd, 2014 on first floor of Siam Center...</p>
            <%= link_to 'read more', grand_opening_news_index_path %>
        </div>
    </div>
</div>
<!-- /.container -->

app/views/shared/_carousel_control.html.erb
<!-- Controls -->
<a class="left carousel-control" href="#myCarousel" data-slide="prev">
  <span class='icon-prev'>
    <%= image_tag 'left_arrow.png' %>
  </span>
</a>
<a class="right carousel-control " href="#myCarousel" data-slide="next">
  <span class='icon-next'>
    <%= image_tag 'right_arrow.png' %>
  </span>
</a>

app/views/terms/terms_and_policies.html.erb
<div class="container full-height">
    <div class="header-title">
        <ul class="list-inline">
            <li>
                <%= link_to 'home', inside_path %>
            </li>
            <li>Terms & Policies</li>
        </ul>
    </div>
    <div class="col-md-12">
        <h1>Beawelry.com Terms of Use</h1>
        <p class="text_justify">
            PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THIS PLATFORM.  The Platform include the Beawelry website and its products and services. By access this Platform via any computer, mobile, tablet, console, or other devices, means you have read, understand and agreed to the Terms of Use and any other applicable law. Beawelry reserves the right to change the Terms of Use in the future which will have immediate effect upon its appearance on the Platform. Your usage of the Platform means you have accepted the updated Terms of Use. If you do not agree to these Terms of Use, please do not use the Platform.
        </p>
        </br>
        <p>
           <b> Intellectual Property</b>
        </p>
        <p class="text_justify">
            All Intellectual Property on this Platform belongs to Beawelry or its licensors. These include material protected by trademarks, copyright and design patents including but not limited to the Beawelry Bear. All trademarks, service marks and trade name including but not limited to word and semi-figurative mark Beawelry®, figurative marks whether registered or not are the exclusive property of and may only be licensed by Beawelry. All other copyrightable contents on the Platform including but not limited to text, images, designs, graphics, scripts, codes, software, application, videos, interactive features and contents are the exclusive property of Beawelry, all rights reserved and enforceable by law.
        </p>
        </br>
        <p>
            <b >Platform Restriction</b>
        </p>
        <p class="text_justify">
            You may use the Platform and its content only for your own non-commercial purpose. If you need to download or print contents from the Platform, you agree to not change or delete any of the ownership notices in those downloads or printed contents. You further agree not to modify, copy, translate, broadcast, perform, display, distribute, frame, reproduce, republish, download, display, post, transmit or sell any Intellectual Property or content appearing on the Platform without Beawelry’s written consent. Also you agree that the usage of any data mining method, computer bot, scraping or similar data collecting methods are not allowed. We reserve the right for law enforcement should you breach our Platform Restriction’s terms of use.
            Product Order
            All the orders process through the Platform are subject to Beawelry‘s acceptance. This mean Beawelry can refuse to proceed the order or cancel the confirmed order, with or without reasons and without liabilities to you or anyone. In case where a credit card has been charged, Beawelry will refund that amount to you.
        </p>
        </p>
        </br>
        <p>
            <b>Links</b>
        </p>
        <p class="text_justify">
            The Platform may contain links to other websites, applications or products or services run by third parties. Beawelry has no control and does not monitor those third parties platform, which may have different terms of use and privacy policies than our Platform. Therefore Beawelry does not accept responsibility and is not liable for the contents of these third parties and their terms of use and privacy policies. Your access to and usage of these contents is at your own risk.
            Privacy
            You can click on our Beawelry Privacy Policy for more detail on our privacy policy, which is also incorporated into these Terms of Use.
        </p>
        </br>
        <p>
            <b> Warrantee Disclaimer </b>
        </p>
        <p class="text_justify">
            Beawelry is not responsible or liable for the messages the user generate through the Platform. Also the contents, materials, and products on the Platform are provided “AS IS” and without warrantee or any kind.  Beawelry does not warrant that the Platform will always be uninterrupted or error-free and its content and material will always be accurate, correct, and reliable and not guarantee that the errors will be corrected. Beawelry also does not warrantee that the Platform and the server will be virus-free or free from other harmful security breach. You agree and understand that any content downloaded is at your own risk and you are responsible for any damage, data loss, or other harm that may incur to your mobile, tablet, computer devices or systems used to access the Platform. Beawelry reserves the right to change any content in the Platform without notice.
        </p>
        </br>
        <p>
            <b>Limitation of Liability</b>
        </p>
        <p class="text_justify">
            BEAWELRY SHALL NOT BE LIABLE FOR ANY DIRECT, SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES, INCLUDING FOR ANY LOST PROFITS OR LOST DATA, THAT RESULT FROM THE USE OF, OR THE INABILITY TO USE, THIS PLATFORM OR THE USAGE OF THE PRODUCTS PURCHASED THROUGH THE PLATFORM OR AT PHYSICAL STORE OR ATTENDANCE AT A BEAWELRY EVENT OR ANY USER GENERATED CONTENT.
            Severability
            If any provision in these Terms of Use is held invalid for some reasons or is deemed unlawful, void or unenforceable, then the remaining provisions of these Terms of Use shall continue to be valid and enforceable.
            Termination
            Beawelry reserves the right to restrict your use of all or any part of the Platform for any or no reason, without notice, and without liability to you or to the other. Beawelry also reserves the right to block users from certain IP addresses or Device numbers and prevent access to the Platform.

        </p>
        </br>
        <h1>Beawelry Privacy Policy</h1>
        <p>
            <b>Information Collected</b>
        </p>
        <p class="text_justify">
            We collect information you agree to give us such as gender, first name, last name, email, telephone, customized message, and your customized design.
        </p>
        </br>
        <p>
           <b> Information Usage</b>
        </p>
        <p class="text_justify">
            We only use your personal information for processing your order and to perform general marketing analysis for further strategy development.
        </p>
        </br>
        <p>
            <b>Information Disclosure</b>
        </p>
        <p class="text_justify">
            Save exceptional circumstances such as request from competent courts to disclose such information, we will not disclose your personal information; including your name, email, phone number, customized message, and your customized design to any third party. And we do not give other companies access to your personal information.
        </p>
        </br>
        <p>
            <b>Information Disclosure by Law</b>
        </p>
        <p class="text_justify">
            We may disclose your information in accordance to law or by government request. We may also share your information to company assisting in fraud protection or investigation.
        </p>
        </br>
        <p>
            <b>Copyright</b>
        </p>
        <p class="text_justify">
            All content on Beawelry websites, including but not limited to articles, photos, moving images and graphics, and your customized design, belongs to and is administrated by Beawelry.
            You are allowed to produce digital or physical copies of the content for your own personal use only.  Also you are allowed to use your predesign or customized design product for your own personal use only. If you use them for other purpose, Beawelry reserved the right to proceed according to appropriate law.
        </p>
        </br>
        <p>
            <b>The newsletter</b>
        </p>
        </p class="text_justify">
            The newsletter will be sent to the email address you provided when you signed up. It is your responsibility to update your personal details, including your e-mail address.
            If you no longer wish to receive the newsletter, you can unsubscribe at any time by using the link in the newsletter.
        </p>
    </div>
</div>
<!-- /.container -->

app/views/welcome/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    controller_path, media: 'all' %>
    <%= stylesheet_link_tag    'main', media: 'all' %>
    <%= stylesheet_link_tag    'cover', media: 'all' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag controller_path %>
    <%= csrf_meta_tags %>
  </head>

<body>
  <div class="site-wrapper">
    <div class="site-wrapper-inner">
      <div class="cover-container">

        <div class="inner cover">
          <div>
            <!-- <img src="/assets/beawelry_logo_2x.png" style="width:448px; height: 198px;"> -->
            <%= image_tag 'beawelry_logo_2x.png', class: '', style: 'width: 448px; height: 198px;' %>
          </div>

          <div style=" margin-top: 50px;">
            <%= link_to coming_soon_path do %>
              <!-- <img src="./images/enter_button_2x.png" style="width:148px; height; 46px;"> -->
              <%= image_tag 'enter_button_2x.png', class: '', style: 'width: 208px; height: 46px;' %>
            <% end %>
          </div>

          <!-- <h1 class="cover-heading">Cover your page.</h1> -->
          <!-- <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p> -->
          <!-- <p class="lead"> -->
          <!-- <a href="#" class="btn btn-lg btn-default">Learn more</a> -->
          <!-- </p> -->
        </div>

        <div class="mastfoot">
          <div class="inner">
            <ul class="nav mastfoot-nav">
              <li ><a href="#">About us</a></li>
              <li>|</li>
              <li><a href="#">Contact</a></li>
              <li>|</li>
              <li><a href="#">Help</a></li>
            </ul>
          </div>
        </div>

      </div>

    </div>
  </div>
</body>

</html>

app/views/welcome/new_coming_soon.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimal-ui" />
    <meta name="description" content="Beawelry reinvents the traditional perception of jewelry; from precious and valuable material to object of emotional representation. We strive to provide the most warming and beautiful experience of giving, receiving, and wearing">
    <meta name="author" content="Beawelry">

    <link rel="shortcut icon" href="<%= asset_path('favicon.ico') %>" type="image/x-icon">
    <link rel="icon" href="<%= asset_path('favicon.ico') %>" type="image/x-icon">

    <title><%= page_title %></title>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'animate', media: 'all' %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
  <script>
    dataLayer = [];
  </script>
  <!-- Google Tag Manager -->
  <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-W9RF2S"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-W9RF2S');</script>
  <!-- End Google Tag Manager -->

  <div class="intro gradient-bg-header">
    <div class="inner">
      <%= image_tag "beawelry_logo.png", class: 'logo animated bounce' %>
      <%= link_to inside_path, 'onclick' => "dataLayer.push({'event': 'entersite'});" do %>
        <%= image_tag 'enter_button_2x.png', class: 'btn-enter' %>
      <% end %>
      <ul class="social">
          <li><a href="https://www.facebook.com/Beawelry"  TARGET="_blank" title="Beawelry's facebook"><i class="fa fa-facebook"></i></a></li>
          <li><a href="http://instagram.com/beawelry" title="Beawelry's instagram"><i class="fa fa-instagram"></i></a></li>
      </ul>
    </div>
  </div>
</body>

</html>